server:
  port: 8903

#actuator暴露接口使用的端口，为了和api接口使用的端口进行分离
#actuator暴露接口的前缀
management:
  port: 8923
  context-path: /
  security:
    enabled: false

logging:
  level:
    com:
      modoo:
        goods: DEBUG
    org:
      springframework:
        web: INFO
  path: log
  file: sys-goods-service.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
